CREATE TABLE IF NOT EXISTS `cms_items` (
  `row_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(100) NOT NULL,
  `collection` VARCHAR(50) NOT NULL,
  `title_en` VARCHAR(500) NOT NULL DEFAULT '',
  `title_ar` VARCHAR(500) NOT NULL DEFAULT '',
  `body_en` MEDIUMTEXT NULL,
  `body_ar` MEDIUMTEXT NULL,
  `subtitle_en` VARCHAR(1000) NOT NULL DEFAULT '',
  `subtitle_ar` VARCHAR(1000) NOT NULL DEFAULT '',
  `image_path` VARCHAR(2000) NOT NULL DEFAULT '',
  `media_path` VARCHAR(2000) NOT NULL DEFAULT '',
  `external_url` VARCHAR(2000) NOT NULL DEFAULT '',
  `program` VARCHAR(200) NOT NULL DEFAULT '',
  `certificate_code` VARCHAR(200) NOT NULL DEFAULT '',
  `certificate_type` VARCHAR(500) NOT NULL DEFAULT '',
  `first_name` VARCHAR(200) NOT NULL DEFAULT '',
  `birthdate` VARCHAR(40) NOT NULL DEFAULT '',
  `published_at` VARCHAR(40) NOT NULL DEFAULT '',
  `published` TINYINT(1) NOT NULL DEFAULT 0,
  `featured` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `filter_id` VARCHAR(100) NOT NULL DEFAULT '',
  `shorts_json` MEDIUMTEXT NULL,
  `created_at` VARCHAR(40) NOT NULL DEFAULT '',
  `updated_at` VARCHAR(40) NOT NULL DEFAULT '',
  PRIMARY KEY (`row_id`),
  UNIQUE KEY `uniq_collection_id` (`collection`, `id`),
  KEY `idx_collection_order` (`collection`, `published`, `sort_order`, `published_at`),
  KEY `idx_certificate_lookup` (`collection`, `program`, `birthdate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
